### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by snikch** [svrakitin/terraform-provider-hydra#1]
Hi there,

I'm looking at using your provider (thank you for building it). One of our requirements is to be able to run it from Terraform Cloud. There's no security mechanism built into the ORY Admin API, which rightfully belongs at the reverse proxy layer. We were hoping to add a basic `Bearer` token to the requests that are sent to the admin API.

Would you be amenable to me creating a pull request which adds an optional configuration / environment variable for setting a Bearer token that would be added to outgoing requests? I'd likely add this as a custom transport provided to the Hydra client.

**Comment by svrakitin** [comment]
@snikch Hi! 

Sure, I can add a section to configure http client and its headers or feel free to submit a PR.

I was also considering using OAuth2 Client Credentials flow for authentication.

**Comment by svrakitin** [comment]
@snikch Released in v0.1.2.

**Comment by snikch** [comment]
Great! Thanks
