### ISSUE TITLE
Skip Consent flag

### ISSUE THREAD

**Issue by somehowchris** [svrakitin/terraform-provider-hydra#13]
Hi :)

Lovely provider 🥂 

Would it be possible to add the "skip_consent" flag as an option?
> Just the cli for reference https://www.ory.sh/docs/hydra/cli/hydra-create-oauth2-client  
> And the client creation endpoint also supports the "skip_consent" flag https://www.ory.sh/docs/hydra/reference/api#tag/oAuth2/operation/createOAuth2Client

I'm really bad at golang and never got to code within a tf provider before, but would love to help out if somebody might hint me where a good starting point would be :)

**Comment by svrakitin** [comment]
Hey @somehowchris, I need to finally update Hydra SDK in order to support this field, I hope to find sometime later this week to work on this unless someone else picks this one.

cc @jgraeger this is something you might find interesting as well

**Comment by nicolasburtey** [comment]
this would be useful for us as well

**Comment by svrakitin** [comment]
`v0.5.1` contains this feature as implmented by @tjorri
