### ISSUE TITLE
client credentials

### ISSUE THREAD

**Issue by nicolasburtey** [svrakitin/terraform-provider-hydra#14]
just to be sure I'm not missing anything, this provider is not enabling client_credentials grant type, is that correct?

if not that would be a relevant use case on our side

**Comment by svrakitin** [comment]
@nicolasburtey `client_credentials` is one of the supported grant types https://github.com/svrakitin/terraform-provider-hydra/blob/57383222233203df03098add5c76c2e02e4aaa13/internal/provider/resource_oauth2_client.go#L108

**Comment by nicolasburtey** [comment]
Yup figured it out thanks!
