### ISSUE TITLE
Making endpoint argument optional

### ISSUE THREAD

**Issue by tjorri** [svrakitin/terraform-provider-hydra#16]
Heya, and really appreciate the provider!

We're facing a case where we are developing a reusable Terraform module, which conditionally would also use the provider to create Hydra OAuth2 clients, but we are facing an issue where the `endpoint` argument is mandatory for the provider.

Our default case is to essentially define the provider as required in the module but hide the actual resources behind feature flags, and in this default case no resources would actually be provisioned and the user of the module might not even need to be aware of the provider. In the case that the user of the module would require OAuth2 clients and indicate it with a flag, they would also then be expected to configure the provider outside of the module with the correct endpoints.

At present this does not work, but I quickly tested with a local provider changing the `endpoint` argument to be `Optional: true`, which allowed our use case to work, albeit it would require some additional sanity checks then on resource management side to more gracefully handle the misconfigured provider.

Would this type of change make sense for you or do you see any fundamental reasons this type of behavior would not be merged if we PR'd something? :)

**Comment by svrakitin** [comment]
Hey @tjorri. You could also set the `endpoint` to a placeholder URL? Like `http://192.0.2.1`

**Comment by tjorri** [comment]
Yeah, I guess we are hitting some limits of Terraform here and the way we are trying to twist it is a bit contrived.

In our case essentially we have a module which wraps various submodules within it, one of which would be for_each'd and would include optionally setting up OAuth2 clients, if appropriate parameters were set, and we were hoping not to force users of the parent module to always have to explicitly set up placeholder provider settings in the project root.

For example, given:

```
# `parent` module:
variable "instances" {
  type = object
  default = {}
}

module "submodule" {
  source = "child"

  for_each = var.instances

  oauth2_clients = try(each.value["oauth2_clients_enabled"], false)
}

# `child` module
terraform {
  required_providers {
    hydra = {
      source  = "svrakitin/hydra"
    }
  }
}

variable "oauth2_clients_enabled" {
  type = bool
}

resource "hydra_oauth2_client" "client" {
  count = var.oauth2_clients_enabled ? 1 : 0

  client_name = "foo"
}
```

In the most elegant case where the user of `parent` had no interest in the clients, we could still have the root project be:

```
module "parent" {
  source = "parent"

  instances = {
    foo = { ... }
    bar = { ... }
  }
}
```

and if the user required the clients to be created, only then we would require configuration of the provider, e.g.:

```
terraform {
  required_providers {
    hydra = {
      source  = "svrakitin/hydra"
    }
  }
}

provider "hydra" {
  endpoint = "https://hydra.endpoint"
}

module "parent" {
  source = "parent"

  instances = {
    foo = { oauth2_clients_enabled = true }
    bar = { ... }
  }
}
```

The first case would require the format of the second even when no clients were needed and in its example form would just fail at lack of provider configuration. We also tried hiding a dummy provider configuration inside `child` module and overriding through explicit module `provider` definitions, but this also hits the wall as providers can't be overridden. Passing provider configs in via variables and configuring in the `child` module might work, but fights against the direction of extracting provider configs into the root module level that Terraform has been going for a few years, IIRC.

But yeah, went through a couple of providers and some sanity checking of sane provider configuration at provider setup is indeed the norm. And I guess what we are trying to achieve is to use Terraform in a way that it's not intended and attempting to twist the provider to make up for the gap with the result likely not being elegant nor intuitive for users of the provider who were not trying to twist things to be more ergonomic for module end users, as in our case.

I'll close this issue since the more I think about it the more I'm convinced that we have to sort our edge case out somehow differently and the initial idea here was fairly opportunistic. :)
